server {
    listen 80;
    server_name localhost;

    proxy_read_timeout 3600s;
    proxy_connect_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering off;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    add_header Access-Control-Allow-Headers '*';

    location / {
        default_type text/plain;
        return 200 'Proxy attivo al 100%';
    }

    location ~* ^/proxy/(https?)/(.*)$ {
        resolver 1.1.1.1 8.8.8.8 valid=300s;
        set $proto $1;
        set $target $2;
        proxy_pass $proto://$target$is_args$args;
        proxy_set_header Host $proxy_host;
        proxy_set_header User-Agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
    }
}
